<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" ignored="3" total="16" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Automation Framework CS PORTAl Test Suite" duration-ms="596528" started-at="2021-01-20T15:33:30 IST" finished-at="2021-01-20T15:43:27 IST">
    <groups>
    </groups>
    <test name="api" duration-ms="4865" started-at="2021-01-20T15:33:30 IST" finished-at="2021-01-20T15:33:35 IST">
      <class name="API.APITest">
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:API.APITest@4ee203eb]" name="methodLevelSetup" is-config="true" duration-ms="1" started-at="2021-01-20T15:33:32 IST" finished-at="2021-01-20T15:33:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="loginAPI(Utils.DataProviders.TestDatabean)[pri:1, instance:API.APITest@4ee203eb]" name="loginAPI" duration-ms="3547" started-at="2021-01-20T15:33:32 IST" data-provider="loginData" finished-at="2021-01-20T15:33:35 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.TestDatabean@7f3fc42f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAPI -->
      </class> <!-- API.APITest -->
    </test> <!-- api -->
    <test name="Login Admin 1 Test" duration-ms="118531" started-at="2021-01-20T15:33:36 IST" finished-at="2021-01-20T15:35:34 IST">
      <class name="tests.LoginTests">
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.LoginTests@68746f22]" name="methodLevelSetup" is-config="true" duration-ms="2" started-at="2021-01-20T15:33:36 IST" finished-at="2021-01-20T15:33:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="LoggingIN(java.lang.reflect.Method, Utils.DataProviders.TestDatabean)[pri:1, instance:tests.LoginTests@68746f22]" name="LoggingIN" duration-ms="118241" started-at="2021-01-20T15:33:36 IST" description="Logging IN" data-provider="loginData" finished-at="2021-01-20T15:35:34 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTests.LoggingIN(java.lang.reflect.Method,Utils.DataProviders.TestDatabean)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Utils.DataProviders.TestDatabean@dc59ec2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoggingIN -->
      </class> <!-- tests.LoginTests -->
    </test> <!-- Login Admin 1 Test -->
    <test name="Customer Interactions TEST" duration-ms="472729" started-at="2021-01-20T15:35:34 IST" finished-at="2021-01-20T15:43:27 IST">
      <class name="tests.widgetsOptionsTest">
        <test-method status="PASS" signature="daDetailsTest(Utils.DataProviders.HeaderDataBean)[pri:1, instance:tests.widgetsOptionsTest@376a0d86]" name="daDetailsTest" duration-ms="21810" started-at="2021-01-20T15:40:39 IST" description="Validating DA Details" data-provider="HeaderData" finished-at="2021-01-20T15:41:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.HeaderDataBean@434c179e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- daDetailsTest -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.widgetsOptionsTest@376a0d86]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:40:39 IST" finished-at="2021-01-20T15:40:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.widgetsOptionsTest@376a0d86]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:41:01 IST" finished-at="2021-01-20T15:41:01 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="FAIL" signature="accumulatorDetailsTest(Utils.DataProviders.HeaderDataBean)[pri:2, instance:tests.widgetsOptionsTest@376a0d86]" name="accumulatorDetailsTest" duration-ms="31278" started-at="2021-01-20T15:41:01 IST" description="Validating Accumulator Details" data-provider="HeaderData" finished-at="2021-01-20T15:41:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.HeaderDataBean@50aa5826]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Accumulator Start Date is not as received in API on row 1 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Next Reset Date Time is not as received in API on row 1 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Start Date is not as received in API on row 2 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Next Reset Date Time is not as received in API on row 2 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Start Date is not as received in API on row 3 expected [Invalid Date String] but found [10-Feb-2021],
Accumulator Next Reset Date Time is not as received in API on row 3 expected [Invalid Date String] but found [10-Feb-2021],
Accumulator Start Date is not as received in API on row 4 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Next Reset Date Time is not as received in API on row 4 expected [Invalid Date String] but found [21-Jan-2021]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Accumulator Start Date is not as received in API on row 1 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Next Reset Date Time is not as received in API on row 1 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Start Date is not as received in API on row 2 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Next Reset Date Time is not as received in API on row 2 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Start Date is not as received in API on row 3 expected [Invalid Date String] but found [10-Feb-2021],
Accumulator Next Reset Date Time is not as received in API on row 3 expected [Invalid Date String] but found [10-Feb-2021],
Accumulator Start Date is not as received in API on row 4 expected [Invalid Date String] but found [21-Jan-2021],
Accumulator Next Reset Date Time is not as received in API on row 4 expected [Invalid Date String] but found [21-Jan-2021]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.widgetsOptionsTest.accumulatorDetailsTest(widgetsOptionsTest.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accumulatorDetailsTest -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.widgetsOptionsTest@376a0d86]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:41:39 IST" finished-at="2021-01-20T15:41:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="FAIL" signature="rechargeHistoryMenuTest(Utils.DataProviders.HeaderDataBean)[pri:5, instance:tests.widgetsOptionsTest@376a0d86]" name="rechargeHistoryMenuTest" duration-ms="30132" started-at="2021-01-20T15:41:39 IST" description="Validating Recharge History&#039;s  Menu" data-provider="HeaderData" finished-at="2021-01-20T15:42:09 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.HeaderDataBean@7a56c3c7]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Date & Time received is not as expected on row 0 expected [Invalid Date String] but found [10-Jan-2021 11:38]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Date & Time received is not as expected on row 0 expected [Invalid Date String] but found [10-Jan-2021 11:38]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.widgetsOptionsTest.rechargeHistoryMenuTest(widgetsOptionsTest.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rechargeHistoryMenuTest -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.widgetsOptionsTest@376a0d86]" name="methodLevelSetup" is-config="true" duration-ms="1" started-at="2021-01-20T15:42:09 IST" finished-at="2021-01-20T15:42:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="FAIL" signature="usageHistoryMenuTest(Utils.DataProviders.HeaderDataBean)[pri:6, instance:tests.widgetsOptionsTest@376a0d86]" name="usageHistoryMenuTest" duration-ms="77299" started-at="2021-01-20T15:42:09 IST" description="Validating Usage History&#039;s  Menu" data-provider="HeaderData" finished-at="2021-01-20T15:43:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.HeaderDataBean@2d4aeaaa]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Sun 17 Jan 2021
12:40:46 PMshould not display before Sun 17 Jan 2021
12:25:29 PM did not expect to find [true] but found [false],
Sun 17 Jan 2021
12:25:29 PMshould not display before Sun 17 Jan 2021
11:27:12 AM did not expect to find [true] but found [false],
Sun 17 Jan 2021
11:27:12 AMshould not display before Sat 16 Jan 2021
08:42:30 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
08:42:30 PMshould not display before Sat 16 Jan 2021
07:48:46 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
07:48:46 PMshould not display before Sat 16 Jan 2021
07:18:51 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
07:18:51 PMshould not display before Sat 16 Jan 2021
03:46:02 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
03:46:02 PMshould not display before Sat 16 Jan 2021
02:43:45 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:43:45 PMshould not display before Sat 16 Jan 2021
02:42:57 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:42:57 PMshould not display before Sat 16 Jan 2021
02:31:45 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:31:45 PMshould not display before Sat 16 Jan 2021
02:23:07 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:23:07 PMshould not display before Sat 16 Jan 2021
02:16:11 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:16:11 PMshould not display before Sat 16 Jan 2021
01:33:56 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
01:33:56 PMshould not display before Sat 16 Jan 2021
01:17:03 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
01:17:03 PMshould not display before Sat 16 Jan 2021
01:08:43 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
01:08:43 PMshould not display before Sat 16 Jan 2021
09:43:31 AM did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Sun 17 Jan 2021
12:40:46 PMshould not display before Sun 17 Jan 2021
12:25:29 PM did not expect to find [true] but found [false],
Sun 17 Jan 2021
12:25:29 PMshould not display before Sun 17 Jan 2021
11:27:12 AM did not expect to find [true] but found [false],
Sun 17 Jan 2021
11:27:12 AMshould not display before Sat 16 Jan 2021
08:42:30 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
08:42:30 PMshould not display before Sat 16 Jan 2021
07:48:46 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
07:48:46 PMshould not display before Sat 16 Jan 2021
07:18:51 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
07:18:51 PMshould not display before Sat 16 Jan 2021
03:46:02 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
03:46:02 PMshould not display before Sat 16 Jan 2021
02:43:45 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:43:45 PMshould not display before Sat 16 Jan 2021
02:42:57 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:42:57 PMshould not display before Sat 16 Jan 2021
02:31:45 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:31:45 PMshould not display before Sat 16 Jan 2021
02:23:07 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:23:07 PMshould not display before Sat 16 Jan 2021
02:16:11 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
02:16:11 PMshould not display before Sat 16 Jan 2021
01:33:56 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
01:33:56 PMshould not display before Sat 16 Jan 2021
01:17:03 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
01:17:03 PMshould not display before Sat 16 Jan 2021
01:08:43 PM did not expect to find [true] but found [false],
Sat 16 Jan 2021
01:08:43 PMshould not display before Sat 16 Jan 2021
09:43:31 AM did not expect to find [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.widgetsOptionsTest.usageHistoryMenuTest(widgetsOptionsTest.java:347)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- usageHistoryMenuTest -->
      </class> <!-- tests.widgetsOptionsTest -->
      <class name="tests.customerInteractionTest">
        <test-method status="PASS" signature="classLevelSetup()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="classLevelSetup" is-config="true" duration-ms="6627" started-at="2021-01-20T15:33:24 IST" finished-at="2021-01-20T15:33:30 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classLevelSetup -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:35:35 IST" finished-at="2021-01-20T15:35:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="openCustomerInteraction(Utils.DataProviders.TestDatabean)[pri:1, instance:tests.customerInteractionTest@38af9828]" name="openCustomerInteraction" duration-ms="31030" started-at="2021-01-20T15:35:35 IST" description="Validate Customer Interaction Page" data-provider="loginData" finished-at="2021-01-20T15:36:06 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.TestDatabean@1d944fc0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openCustomerInteraction -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:36:06 IST" finished-at="2021-01-20T15:36:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method name="validateDemographicInformation" signature="validateDemographicInformation(Utils.DataProviders.TestDatabean)[pri:2, instance:tests.customerInteractionTest@38af9828]" status="FAIL" duration-ms="210508" finished-at="2021-01-20T15:39:36 IST" started-at="2021-01-20T15:36:06 IST" depends-on-methods="tests.customerInteractionTest.openCustomerInteraction" data-provider="loginData" description="Validating Demographic Info">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.TestDatabean@5606d537]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Customer's Airtel Money Status is not visible no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="customer-details"]//div[@class="top col-md-7"]/div/div[3]//li[2]//p[1]//span[2]"}
  (Session info: headless chrome=87.0.4280.141)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '4.0.0-alpha-3', revision: '8c567de6dc'
System info: host: 'LT2394650', ip: '172.23.64.204', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.141, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\2394650\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:64383}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 534c9180d1b4c5ac86c2663aeb48b53c
*** Element info: {Using=xpath, value=//div[@class="customer-details"]//div[@class="top col-md-7"]/div/div[3]//li[2]//p[1]//span[2]},
Customer's Airtel Money Service Status is not visible no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="customer-details"]//div[@class="top col-md-7"]/div/div[3]//li[2]//p[2]//span[2]"}
  (Session info: headless chrome=87.0.4280.141)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '4.0.0-alpha-3', revision: '8c567de6dc'
System info: host: 'LT2394650', ip: '172.23.64.204', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.141, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\2394650\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:64383}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 534c9180d1b4c5ac86c2663aeb48b53c
*** Element info: {Using=xpath, value=//div[@class="customer-details"]//div[@class="top col-md-7"]/div/div[3]//li[2]//p[2]//span[2]}]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Customer's Airtel Money Status is not visible no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="customer-details"]//div[@class="top col-md-7"]/div/div[3]//li[2]//p[1]//span[2]"}
  (Session info: headless chrome=87.0.4280.141)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '4.0.0-alpha-3', revision: '8c567de6dc'
System info: host: 'LT2394650', ip: '172.23.64.204', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.141, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\2394650\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:64383}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 534c9180d1b4c5ac86c2663aeb48b53c
*** Element info: {Using=xpath, value=//div[@class="customer-details"]//div[@class="top col-md-7"]/div/div[3]//li[2]//p[1]//span[2]},
Customer's Airtel Money Service Status is not visible no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="customer-details"]//div[@class="top col-md-7"]/div/div[3]//li[2]//p[2]//span[2]"}
  (Session info: headless chrome=87.0.4280.141)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '4.0.0-alpha-3', revision: '8c567de6dc'
System info: host: 'LT2394650', ip: '172.23.64.204', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.141, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\2394650\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:64383}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 534c9180d1b4c5ac86c2663aeb48b53c
*** Element info: {Using=xpath, value=//div[@class="customer-details"]//div[@class="top col-md-7"]/div/div[3]//li[2]//p[2]//span[2]}
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.customerInteractionTest.validateDemographicInformation(customerInteractionTest.java:317)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDemographicInformation -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:39:37 IST" finished-at="2021-01-20T15:39:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="invalidMSISDNTest()[pri:3, instance:tests.customerInteractionTest@38af9828]" name="invalidMSISDNTest" duration-ms="8492" started-at="2021-01-20T15:39:37 IST" description="As an agent I want capability to check if an MSISDN is valid or invalid" finished-at="2021-01-20T15:39:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidMSISDNTest -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="methodLevelSetup" is-config="true" duration-ms="1" started-at="2021-01-20T15:39:46 IST" finished-at="2021-01-20T15:39:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="openCustomerInteractionAPI(Utils.DataProviders.TestDatabean)[pri:4, instance:tests.customerInteractionTest@38af9828]" name="openCustomerInteractionAPI" duration-ms="37943" started-at="2021-01-20T15:39:46 IST" description="Validate Customer Interaction Page" data-provider="loginData" finished-at="2021-01-20T15:40:24 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.TestDatabean@3efb863c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openCustomerInteractionAPI -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:40:24 IST" finished-at="2021-01-20T15:40:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="FAIL" signature="yourCurrentBalanceWidgetTest()[pri:6, instance:tests.customerInteractionTest@38af9828]" name="yourCurrentBalanceWidgetTest" duration-ms="4513" started-at="2021-01-20T15:40:24 IST" description="Validating Current Balance Widget" finished-at="2021-01-20T15:40:28 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Data Expiry Date is not as Received in API  expected [01-01-1970] but found [-]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Data Expiry Date is not as Received in API  expected [01-01-1970] but found [-]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.customerInteractionTest.yourCurrentBalanceWidgetTest(customerInteractionTest.java:441)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- yourCurrentBalanceWidgetTest -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:40:29 IST" finished-at="2021-01-20T15:40:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="PASS" signature="usageHistoryWidgetTest(Utils.DataProviders.HeaderDataBean)[pri:7, instance:tests.customerInteractionTest@38af9828]" name="usageHistoryWidgetTest" duration-ms="6009" started-at="2021-01-20T15:40:29 IST" description="Validating Usage History Widget" data-provider="HeaderData" finished-at="2021-01-20T15:40:35 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.HeaderDataBean@192b76a4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- usageHistoryWidgetTest -->
        <test-method status="PASS" signature="methodLevelSetup()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="methodLevelSetup" is-config="true" duration-ms="0" started-at="2021-01-20T15:40:35 IST" finished-at="2021-01-20T15:40:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method status="FAIL" signature="rechargeHistoryWidgetTest(Utils.DataProviders.HeaderDataBean)[pri:8, instance:tests.customerInteractionTest@38af9828]" name="rechargeHistoryWidgetTest" duration-ms="3199" started-at="2021-01-20T15:40:35 IST" description="Validating Recharge History Widget" data-provider="HeaderData" finished-at="2021-01-20T15:40:38 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Utils.DataProviders.HeaderDataBean@1b62ad1e]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Recharge History Date Time is not As received in API for row number 0 expected [Invalid Date String] but found [10-Jan-2021 11:38]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Recharge History Date Time is not As received in API for row number 0 expected [Invalid Date String] but found [10-Jan-2021 11:38]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.customerInteractionTest.rechargeHistoryWidgetTest(customerInteractionTest.java:522)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rechargeHistoryWidgetTest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:tests.customerInteractionTest@38af9828]" name="teardown" is-config="true" duration-ms="605" started-at="2021-01-20T15:43:28 IST" finished-at="2021-01-20T15:43:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.customerInteractionTest -->
    </test> <!-- Customer Interactions TEST -->
  </suite> <!-- Automation Framework CS PORTAl Test Suite -->
</testng-results>
